import Header from '@/components/header/Header'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const popins = Poppins({
	subsets: ['latin'],
	weight: ['400', '500', '700', '800'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ru">
			<body className={popins.className}>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	)
}
